CXX = g++
CXXFLAGS = -Wall -ansi -pedantic -g -std=c++11

all: CacheSimulatorLab1

CacheSimulatorLab1: main.cpp AddressSplit.cpp AddressSplit.h
	$(CXX) $(CXXFLAGS) -o CacheSimulatorLab1 main.cpp AddressSplit.cpp
